name: service
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  models:
    path: ../models

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
